require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OrderPaymentsController do

  def mock_order_payment(stubs={})
    @mock_order_payment ||= mock_model(OrderPayment, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all order_payments as @order_payments" do
      OrderPayment.stub(:all) { [mock_order_payment] }
      get :index
      assigns(:order_payments).should eq([mock_order_payment])
    end
  end

  describe "GET show" do
    it "assigns the requested order_payment as @order_payment" do
      OrderPayment.stub(:find).with("37") { mock_order_payment }
      get :show, :id => "37"
      assigns(:order_payment).should be(mock_order_payment)
    end
  end

  describe "GET new" do
    it "assigns a new order_payment as @order_payment" do
      OrderPayment.stub(:new) { mock_order_payment }
      get :new
      assigns(:order_payment).should be(mock_order_payment)
    end
  end

  describe "GET edit" do
    it "assigns the requested order_payment as @order_payment" do
      OrderPayment.stub(:find).with("37") { mock_order_payment }
      get :edit, :id => "37"
      assigns(:order_payment).should be(mock_order_payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created order_payment as @order_payment" do
        OrderPayment.stub(:new).with({'these' => 'params'}) { mock_order_payment(:save => true) }
        post :create, :order_payment => {'these' => 'params'}
        assigns(:order_payment).should be(mock_order_payment)
      end

      it "redirects to the created order_payment" do
        OrderPayment.stub(:new) { mock_order_payment(:save => true) }
        post :create, :order_payment => {}
        response.should redirect_to(order_payment_url(mock_order_payment))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved order_payment as @order_payment" do
        OrderPayment.stub(:new).with({'these' => 'params'}) { mock_order_payment(:save => false) }
        post :create, :order_payment => {'these' => 'params'}
        assigns(:order_payment).should be(mock_order_payment)
      end

      it "re-renders the 'new' template" do
        OrderPayment.stub(:new) { mock_order_payment(:save => false) }
        post :create, :order_payment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested order_payment" do
        OrderPayment.stub(:find).with("37") { mock_order_payment }
        mock_order_payment.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :order_payment => {'these' => 'params'}
      end

      it "assigns the requested order_payment as @order_payment" do
        OrderPayment.stub(:find) { mock_order_payment(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:order_payment).should be(mock_order_payment)
      end

      it "redirects to the order_payment" do
        OrderPayment.stub(:find) { mock_order_payment(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(order_payment_url(mock_order_payment))
      end
    end

    describe "with invalid params" do
      it "assigns the order_payment as @order_payment" do
        OrderPayment.stub(:find) { mock_order_payment(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:order_payment).should be(mock_order_payment)
      end

      it "re-renders the 'edit' template" do
        OrderPayment.stub(:find) { mock_order_payment(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested order_payment" do
      OrderPayment.stub(:find).with("37") { mock_order_payment }
      mock_order_payment.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the order_payments list" do
      OrderPayment.stub(:find) { mock_order_payment }
      delete :destroy, :id => "1"
      response.should redirect_to(order_payments_url)
    end
  end

end
